### ISSUE TITLE
404 for pre-built Docker image

### ISSUE THREAD

**Issue by astrostl** [randsleadershipslack/destalinator#170] opened 2018-02-17 19:50 UTC
https://hub.docker.com/r/randsleadershipslack/destalinator/ returns a 404.

**Comment by kmarekspartz** [comment] 2018-02-18 01:09
Thanks! The link was added by @TheConnMan in advance of someone putting an image there. I don't think anyone has gotten around to that.  @TheConnMan may have the image namespaced elsewhere, but otherwise this is duplicate of #139.

**Closed by kmarekspartz** 2018-02-18 01:09 UTC

**Comment by TheConnMan** [comment] 2018-02-18 15:15
No, I don't have an up to date image anywhere else.
